### ISSUE TITLE
按n键时就会跳出

### ISSUE THREAD

**Issue by silvernoo** [turingou/douban.fm#114]
在切换歌曲时会偶尔出现跳出现象。

> [../deps/mpg123/src/output/alsa.c:165] error: cannot open device default
> 
> events.js:72
>        throw er; // Unhandled 'error' event
>              ^
> Error: open() failed: -1
>    at Speaker._open >(/usr/local/lib/node_modules/douban.fm/node_modules/player/node_modules/sp>eaker/index.js:106:11)
>    at Speaker._write (/usr/local/lib/node_modules/douban.fm/node_modules/player/node_modules/sp>eaker/index.js:182:21)
>    at doWrite (_stream_writable.js:221:10)
>    at writeOrBuffer (_stream_writable.js:211:5)
>    at Speaker.Writable.write (_stream_writable.js:180:11)
>    at write (_stream_readable.js:583:24)
>    at flow (_stream_readable.js:592:7)
>    at Decoder.pipeOnReadable (_stream_readable.js:624:5)
>    at Decoder.EventEmitter.emit (events.js:92:17)
>    at emitReadable_ (_stream_readable.js:408:10)
>    at emitReadable (_stream_readable.js:404:5)
>    at readableAddChunk (_stream_readable.js:165:9)

**Comment by zhongkun** [comment]
0.3.0里还有这个问题
