### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by Angdo** [turingou/douban.fm#139]
开发版无法安装（稳定版也不行）
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/douban.fm/node_modules/player/node_modules/speaker
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "git://github.com/turingou/douban.fm.git" "-g" "--disturl=http://dist.u.qiniudn.com" "--registry=http://r.cnpmjs.org"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! lame@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

**Comment by turingou** [comment]
因依赖问题，暂不支持 node `v0.10+` 的版本

**Comment by jptiancai** [comment]
@turingou  我的也是这样 ubuntu OS 14.04(32bit)

**Comment by CaptainFeng** [comment]
请问支持多少版本以内呢

**Comment by zhangda89** [comment]
好吧 你都开始玩 ES6 这个node的新版本 也应该支持一下吧 
列个表吧  支持哪个版本的

**Comment by reliveyy** [comment]
同样问题

**Comment by dragonwong** [comment]
关注:family:

**Comment by meteormatt** [comment]
似乎到现在都没有修复?

``` bash
/Users/Meteor/.node-gyp/4.2.1/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
1 error generated.
make: *** [Release/obj.target/bindings/src/bindings.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Meteor/.nvm/versions/node/v4.2.1/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/Meteor/.nvm/versions/node/v4.2.1/bin/node" "/Users/Meteor/.nvm/versions/node/v4.2.1/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Meteor/.nvm/versions/node/v4.2.1/lib/node_modules/douban.fm/node_modules/player/node_modules/lame
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/Meteor/.nvm/versions/node/v4.2.1/bin/node" "/Users/Meteor/.nvm/versions/node/v4.2.1/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/Meteor/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/Meteor/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/Users/Meteor/.nvm/versions/node/v4.2.1/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "install" "douban.fm" "-g"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE

npm ERR! speaker@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the speaker@0.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Meteor/npm-debug.log
```
